export const defaultMapping = {
  'API Gateway': 'API GW',
  'Application Discovery Service': 'ADS',
  'AppStream 2.0': 'AppStream',
  'AWS Auto Scaling': 'ASG',
  'Certificate Manager': 'ACM',
  CloudFormation: 'CFN',
  CloudFront: 'CF',
  CloudHSM: 'HSM',
  CloudSearch: 'CS',
  CloudWatch: 'CW',
  'Database Migration Service': 'DMS',
  'Direct Connect': 'DX',
  DynamoDB: 'DDB',
  'Elastic Beanstalk': 'EB',
  'Elastic Container Registry': 'ECR',
  'Elastic Container Service': 'ECS',
  'Elastic Kubernetes Service': 'EKS',
  'IoT Device Management': 'IoT DM',
  'Key Management Service': 'KMS',
  'Managed Apache Airflow': 'MAA',
  'Resource Access Manager': 'RAM',
  'Route 53': 'R53',
  'Service Catalog': 'SC',
  'Simple Notification Service': 'SNS',
  'Simple Queue Service': 'SQS',
  'Step Functions': 'SF',
  'Storage Gateway': 'SG',
  'Systems Manager': 'SSM',
  'Trusted Advisor': 'TA',
  'WAF & Shield': 'WAF',
};
