export const defaultMapping = {
  'API Gateway': 'API GW',
  'Application Discovery Service': 'ADS',
  'Application Migration Service': 'MGN',
  'AppStream 2.0': 'AppStream',
  'AWS Auto Scaling': 'ASG',
  'Billing and Cost Management': 'Billing',
  'Certificate Manager': 'ACM',
  'CloudFormation': 'Cfn',
  'CloudFront': 'CF',
  'CloudHSM': 'HSM',
  'CloudSearch': 'CS',
  'CloudTrail': 'CTr',
  'CloudWatch': 'CW',
  'Compute Optimizer': 'Opt',
  'Data Firehose': 'Firehose',
  'Database Migration Service': 'DMS',
  'Direct Connect': 'DX',
  'DynamoDB': 'DDB',
  'Elastic Beanstalk': 'EB',
  'Elastic Container Registry': 'ECR',
  'Elastic Container Service': 'ECS',
  'Elastic Kubernetes Service': 'EKS',
  'IoT Device Management': 'IoT DM',
  'Key Management Service': 'KMS',
  'Managed Apache Airflow': 'MAA',
  'OpenSearch Service': 'OpenSearch',
  'Resource Access Manager': 'RAM',
  'Route 53': 'R53',
  'Service Catalog': 'SC',
  'Secrets Manager': 'Secrets',
  'Simple Email Service': 'SES',
  'Simple Notification Service': 'SNS',
  'Simple Queue Service': 'SQS',
  'Step Functions': 'Sfn',
  'Storage Gateway': 'SG',
  'Systems Manager': 'SSM',
  'Trusted Advisor': 'TA',
  'WAF & Shield': 'WAF',
};
